package com.example.accessingdatamysql;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMapping'
import org.springframework.web.bind.annotation.ResponseBody;

@Controller // This means that this class is a Controllwe
@RequestMapping(path="/demo") // This means URL's start with /demo (after Application Path)
public class MainController
{
	@Autowired // This means to get the bean called userRepository
		//Which is auto-generated by Spring, we will use it to handle the data
	private UserRepository userRepository;

	@postMapping(path="/add") //Map ONLY POST Requests
	public @ResponseBody String addNewUser (@RequestParam String name, @RequestParam String email)
	{
		// @ResponseBody means the returned String is the response, not a view name
		// @RequestParam means it is a parameter from the GET or POST request
		
		User n = new User();
		n.setName(name);
		n.setEmail(email);
		userRepository.save(n);
		return "Saved";
	}

	@GetMapping(path="/all")
	public @ResponseBody Iterable<User> getAllUsers()
	{
		return userRepository.findAll();
	}
}
